name: ROS 2 CI Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: nav_path_recorder
          target-ros2-distro: jazzy
          vcs-repo-file-url: dependencies.repos
